version = 1

test_patterns = [
  "*/test/**"
]

exclude_patterns = [
  "setup.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"