name: Lint and Test
on: push

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Set up uv with Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - run: uv sync --locked --dev
      - run: uv run ruff check .
      - name: Run pyrefly if on 3.14, ty otherwise
        run: |
          if [[ '${{ matrix.python-version }}' == 3.14* ]]; then
            echo "Using pyrefly for Python 3.14"
            uv run --with pyrefly pyrefly check graphviz2drawio
          else
            uv run --with ty ty check graphviz2drawio
          fi
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
      - run: uv run pytest --cov
