name: Publish Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
      with:
        python-version: '3.11'
    - name: Create dist
      run: uv build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
