name: Spec Test
on: push

permissions:
  contents: read

jobs:
  spec-test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: brew install graphviz
      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
        with:
          python-version: "3.12"
          enable-cache: true
      - run: |
          export CFLAGS="-I$(brew --prefix graphviz)/include"
          export LDFLAGS="-L$(brew --prefix graphviz)/lib"
          uv sync --locked
      - name: Run specs tests script
        run: |
          mkdir tmp_out
          uv run ./test_specs.sh test/ specs/ tmp_out/
