name: Spec Test
on: push

permissions:
  contents: read

jobs:
  spec-test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        id: cpython3
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements.txt
      - run: brew install graphviz
      - run: pip install -r requirements.txt
      - name: Run specs tests script
        run: |
          mkdir tmp_out
          ./test_specs.sh test/ specs/ tmp_out/
